package com.example.core

const val SINGLE_ERROR_TITLE = "UNE ERREUR EST SURVENUE A CAUSE DE LA RAISON SUIVANTE :\n\n"
const val ERRORS_TITLE = "UNE ERREUR EST SURVENUE A CAUSE DES RAISONS SUIVANTES :\n\n"

const val WORD_1_ERROR = "CHAMP MOT 1 VIDE ou INCORRECT\n\n"
const val WORD_2_ERROR = "CHAMP MOT 2 VIDE ou INCORRECT\n\n"
const val NUMBER_1_ERROR = "CHAMP NUMBER 1 VIDE ou INCORRECT\n\n"
const val NUMBER_2_ERROR = "CHAMP NUMBER 2 VIDE ou INCORRECT\n\n"
const val LIMIT_ERROR = "CHAMP LIMITE VIDE ou INCORRECT"