package com.example.core

const val SINGLE_ERROR_TITLE = "UNE ERREUR EST SURVENUE A CAUSE DE LA RAISON SUIVANTE :\n\n"
const val ERRORS_TITLE = "UNE ERREUR EST SURVENUE A CAUSE DES RAISONS SUIVANTES :\n\n"

const val WORD_1_ERROR = "CHAMP MOT 1 VIDE ou INCORRECT\n\n"
const val WORD_2_ERROR = "CHAMP MOT 2 VIDE ou INCORRECT\n\n"
const val NUMBER_1_ERROR = "CHAMP NUMBER 1 VIDE ou INCORRECT\n\n"
const val NUMBER_2_ERROR = "CHAMP NUMBER 2 VIDE ou INCORRECT\n\n"
const val LIMIT_ERROR = "CHAMP LIMITE VIDE ou INCORRECT"

const val SHARED_PREF_WORD_ONE = "SHARED_PREF_WORD_ONE"
const val SHARED_PREF_WORD_TWO = "SHARED_PREF_WORD_TWO"
const val SHARED_PREF_NUMBER_ONE = "SHARED_PREF_NUMBER_ONE"
const val SHARED_PREF_NUMBER_TWO = "SHARED_PREF_NUMBER_TWO"
const val SHARED_PREF_LIMIT = "SHARED_PREF_LIMIT"
const val SHARED_PREF_WORD_ONE_VALUE = "SHARED_PREF_WORD_ONE_VALUE"
const val SHARED_PREF_WORD_TWO_VALUE = "SHARED_PREF_WORD_TWO_VALUE"
const val SHARED_PREF_NUMBER_ONE_VALUE = "SHARED_PREF_NUMBER_ONE_VALUE"
const val SHARED_PREF_NUMBER_TWO_VALUE = "SHARED_PREF_NUMBER_TWO_VALUE"
const val SHARED_PREF_LIMIT_VALUE = "SHARED_PREF_LIMIT_VALUE"